DROP TABLE IF EXISTS prices;
DROP TABLE IF EXISTS products;

CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  description VARCHAR(500)
);

CREATE TABLE prices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL,
  price_value NUMERIC(19, 2) NOT NULL,
  init_date DATE NOT NULL,
  end_date DATE,
  CONSTRAINT fk_prices_product FOREIGN KEY (product_id) REFERENCES products (id),
  CONSTRAINT chk_prices_value_positive CHECK (price_value > 0),
  CONSTRAINT chk_prices_date_range CHECK (end_date IS NULL OR init_date < end_date)
);

CREATE INDEX idx_prices_product_id ON prices (product_id);
CREATE INDEX idx_prices_product_date_range ON prices (product_id, init_date, end_date);
